### ISSUE TITLE
How to specify constraints?

### ISSUE THREAD

**Issue by MichaelZhouwang** [raymondhs/constrained-levt#1]
Hi, I would like to employ the method in my own dataset. But I cannot figure out how to spe. cify constraints. In the readme, the input newstest2014-wikt.en does not seems to contain any constraints. Thanks in advance.

**Comment by raymondhs** [comment]
Hello, the format of the input file is tab-separated, where the first column corresponds to the source text and the remaining columns for the constraints. Each constraint is in this format: `source|||target`. The input should be tokenized first (including BPE). For instance:

`The older light systems consu@@ me around 100 Wat@@ ts .\tconsu@@ me|||ver@@ brauchen`

**Comment by MichaelZhouwang** [comment]
> Hello, the format of the input file is tab-separated, where the first column corresponds to the source text and the remaining columns for the constraints. Each constraint is in this format: `source|||target`. The input should be tokenized first (including BPE). For instance:
> 
> `The older light systems consu@@ me around 100 Wat@@ ts .\tconsu@@ me|||ver@@ brauchen`

Thanks for your quick response! It works well!
