### ISSUE TITLE
Could you please provide original dataset and dict in your experiment?

### ISSUE THREAD

**Issue by edwardelric1202** [raymondhs/constrained-levt#5]
Hi, I tried to replicte your experiment, it worked, but I want to compare it with original data in BLEU score, so I want to use the original training set to generate data using fairseq, could you provide it? Thank you!

**Comment by raymondhs** [comment]
Hello, we trained the LevT model using the distilled training set released by Gu et al. You can find their released datasets [here](https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation#download). It has both the original and distillation datasets.

**Comment by edwardelric1202** [comment]
> Hello, we trained the LevT model using the distilled training set released by Gu et al. You can find their released datasets [here](https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation#download). It has both the original and distillation datasets.

Ok, Thanks a lot!
